# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      #name: Docker-AgentPool 
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          export AWS_ACCESS_KEY_ID=AKIA5G272AGK3S6EEA73
          export AWS_SECRET_ACCESS_KEY=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
          export AWS_DEFAULT_REGION=me-central-1
    - task: CmdLine@2
      inputs:
        script: 'aws ecr get-login-password --region me-central-1 | docker login --username AWS --password-stdin 908049645973.dkr.ecr.me-central-1.amazonaws.com'
    
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/tesseractDocker/Dockerfile'
        tags: |
          $(tag)
        buildContext: '$(Build.SourcesDirectory)'
        repository: '908049645973.dkr.ecr.me-central-1.amazonaws.com/eks-sit1-ecr01'

    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'awsCredentialsADCB'
        regionName: 'me-central-1'
        imageSource: 'imagename'
        sourceImageName: '908049645973.dkr.ecr.me-central-1.amazonaws.com/eks-sit1-ecr01'
        sourceImageTag: $(Build.BuildId)
        pushTag: $(Build.BuildId)
        repositoryName: 'eks-sit1-ecr01'
        globExpressions: 'Dockerfile'